# Generated by Django 2.2.10 on 2020-02-10 10:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200210_1035'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.City', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT (37.6198482461064785 55.7535037511883829)', srid=4326, verbose_name='location'),
        ),
    ]
