# Generated by Django 2.2.12 on 2020-05-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20200214_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simbalance',
            options={'ordering': ('ctime',), 'verbose_name': 'sim balance', 'verbose_name_plural': 'sim balance'},
        ),
    ]
