# Generated by Django 2.2.13 on 2020-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20200507_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='errortype',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='title'),
        ),
    ]
