# Generated by Django 2.2.13 on 2020-07-28 13:58

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20200609_1145'),
        ('core', '0008_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sector',
            field=smart_selects.db_fields.GroupedForeignKey(default=None, group_field='company', on_delete=django.db.models.deletion.PROTECT, to='core.Sectors', verbose_name='sector'),
            preserve_default=False,
        ),
    ]
