# Generated by Django 2.2.13 on 2020-08-03 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_sensor_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('level_detection_max_range', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('level_measurement_max_range', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('description_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='range_to_bin_bottom',
        ),
        migrations.AddField(
            model_name='sensor',
            name='measures_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='container_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='container_type_sensors', to='sensors.ContainerType', verbose_name='container type'),
            preserve_default=False,
        ),
    ]
