# Generated by Django 2.2.13 on 2020-08-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wastetype'),
        ('sensors', '0009_auto_20200803_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='waste_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.WasteType', verbose_name='waste type'),
            preserve_default=False,
        ),
    ]
