# Generated by Django 2.2.13 on 2020-08-25 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_sensor_waste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('mtime', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('UPDATE_CONFIG', 'Update Configuration'), ('FETCH_CONFIG', 'Fetch Configuration'), ('GET_LOCATION', 'Determine GPS location'), ('GET_SIM_BALANCE', 'Determine SIM balance'), ('GET_PHONE_NUMBER', 'Determine phone number')], max_length=32)),
                ('payload', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('SUCCESS', 'Successful job'), ('FAILURE', 'Failed job')], max_length=16)),
                ('result', models.CharField(blank=True, max_length=100)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor')),
            ],
        ),
    ]
