# Generated by Django 2.2.13 on 2020-08-27 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_sensorjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorsettingsprofile',
            name='connections_per_day',
        ),
        migrations.RemoveField(
            model_name='sensorsettingsprofile',
            name='data_topic',
        ),
        migrations.RemoveField(
            model_name='sensorsettingsprofile',
            name='jobs_topic',
        ),
        migrations.RemoveField(
            model_name='sensorsettingsprofile',
            name='min_battery_voltage',
        ),
        migrations.RemoveField(
            model_name='sensorsettingsprofile',
            name='phone_number_query',
        ),
        migrations.RemoveField(
            model_name='sensorsettingsprofile',
            name='receive_timeout',
        ),
        migrations.RemoveField(
            model_name='sensorsettingsprofile',
            name='send_timeout',
        ),
        migrations.RemoveField(
            model_name='sensorsettingsprofile',
            name='shutdown_max_temp',
        ),
        migrations.RemoveField(
            model_name='sensorsettingsprofile',
            name='sim_balance_query',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='payload',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='topic',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorsettingsprofile',
            name='bin_tilt_angle',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='sensorsettingsprofile',
            name='gsm_timeout',
            field=models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='sensorsettingsprofile',
            name='measurement_interval',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='sensorsettingsprofile',
            name='measurement_profile',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='sensorsettingsprofile',
            name='measurement_range_max',
            field=models.IntegerField(default=7000, validators=[django.core.validators.MinValueValidator(180), django.core.validators.MaxValueValidator(7000)]),
        ),
        migrations.AddField(
            model_name='sensorsettingsprofile',
            name='measurement_range_min',
            field=models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(180), django.core.validators.MaxValueValidator(7000)]),
        ),
        migrations.AddField(
            model_name='sensorsettingsprofile',
            name='measurement_samples',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='sensorjob',
            name='payload',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='sensorjob',
            name='result',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='sensorsettingsprofile',
            name='fire_min_temp',
            field=models.IntegerField(default=80, help_text='in celsius (C)', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sensorsettingsprofile',
            name='gps_timeout',
            field=models.IntegerField(default=120, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='sensorsettingsprofile',
            name='login',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='sensorsettingsprofile',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='sensorsettingsprofile',
            name='server_host',
            field=models.CharField(max_length=64),
        ),
    ]
