# Generated by Django 2.2.13 on 2020-09-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_auto_20200827_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errortype',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='code error'),
        ),
    ]
