# Generated by Django 2.2.13 on 2020-09-07 09:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0013_auto_20200901_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerneMQAuthAcl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountpoint', models.CharField(max_length=10)),
                ('client_id', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('publish_acl', django.contrib.postgres.fields.jsonb.JSONField()),
                ('subscribe_acl', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'vmq_auth_acl',
                'unique_together': {('mountpoint', 'client_id', 'username')},
            },
        ),
    ]
