# Generated by Django 2.2.13 on 2020-09-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wastetype'),
        ('sensors', '0014_vernemqauthacl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsAuthCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
        ),
    ]
