# Generated by Django 2.2.13 on 2020-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_sensorsauthcredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='hardware_identity',
            field=models.CharField(max_length=50, unique=True, verbose_name='hardware identity'),
        ),
    ]
