# Generated by Django 2.2.16 on 2020-09-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0016_auto_20200918_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorjob',
            name='payload',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
