# Generated by Django 2.2.16 on 2020-09-25 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensors', '0018_companysensorslicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseBalanceTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('operation', models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('DEPOSIT', 'Deposit')], max_length=16)),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=128)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_log', to='sensors.CompanySensorsLicense')),
            ],
        ),
    ]
