# Generated by Django 2.2.16 on 2020-09-28 10:28

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0019_licensebalancetransactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsLicenseKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('period_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('devices_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('mtime', models.DateTimeField(blank=True, null=True, verbose_name='modified at')),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
