# Generated by Django 2.2.16 on 2020-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0020_sensorslicensekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='hardware_identity',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sensorslicensekey',
            name='mtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
