# Generated by Django 2.2.16 on 2020-10-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0021_auto_20201008_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='autogenerate_data',
            field=models.BooleanField(default=False),
        ),
    ]
