# Generated by Django 2.2.16 on 2020-10-19 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0022_sensor_autogenerate_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorOnboardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_identity', models.CharField(max_length=50, unique=True)),
                ('install_type', models.CharField(blank=True, choices=[('FRONT', 'Front'), ('REAR', 'Rear')], max_length=16)),
                ('network_type', models.CharField(blank=True, choices=[('2G', '2G')], max_length=16)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('mtime', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
    ]
