# Generated by Django 2.2.16 on 2020-10-29 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0023_sensoronboardrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containertype',
            name='level_detection_max_range',
        ),
        migrations.RemoveField(
            model_name='containertype',
            name='level_measurement_max_range',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='measures_level',
        ),
        migrations.AddField(
            model_name='containertype',
            name='diagonal_mount_max_range',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='containertype',
            name='horizontal_mount_max_range',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='containertype',
            name='vertical_mount_max_range',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mount_type',
            field=models.CharField(choices=[('HORIZONTAL', 'Horizontal'), ('VERTICAL', 'Vertical'), ('DIAGONAL', 'Diagonal')], default='HORIZONTAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
