# Generated by Django 2.2.17 on 2021-03-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0024_auto_20201029_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoronboardrequest',
            name='network_type',
            field=models.CharField(blank=True, choices=[('2G', '2G'), ('NB_IOT', 'NB-IoT')], max_length=16),
        ),
    ]
