# Generated by Django 2.2.17 on 2021-05-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0026_sensor_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorjob',
            name='type',
            field=models.CharField(choices=[('UPDATE_CONFIG', 'Update Configuration'), ('FETCH_CONFIG', 'Fetch Configuration'), ('GET_LOCATION', 'Determine GPS location'), ('UPDATE_FIRMWARE', 'Update firmware'), ('GET_SIM_BALANCE', 'Determine SIM balance'), ('GET_PHONE_NUMBER', 'Determine phone number')], max_length=32),
        ),
    ]
