# Generated by Django 2.2.17 on 2021-05-31 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0027_auto_20210527_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['serial_number']},
        ),
    ]
