# Generated by Django 2.2.17 on 2021-06-24 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0028_auto_20210531_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='vertical_mount_min_range',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
