# Generated by Django 2.2.17 on 2021-09-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0029_containertype_vertical_mount_min_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorPilot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sensors.sensor',),
        ),
    ]
