# Generated by Django 2.2.17 on 2022-04-27 10:08

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0030_sensorpilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='account_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sim_number',
            field=models.CharField(blank=True, help_text='Only numbers allowed', max_length=20, validators=[django.core.validators.RegexValidator(re.compile('\\d+'))]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Only numbers allowed', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('\\d+'))], verbose_name='phone number'),
        ),
    ]
