# Generated by Django 2.2.17 on 2022-09-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0031_auto_20220427_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullness',
            name='signal_amp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
