# Generated by Django 2.2.17 on 2022-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0033_auto_20221026_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorjob',
            name='type',
            field=models.CharField(choices=[('UPDATE_CONFIG', 'Update Configuration'), ('FETCH_CONFIG', 'Fetch Configuration'), ('GET_LOCATION', 'Determine GPS location'), ('UPDATE_FIRMWARE', 'Update firmware'), ('GET_SIM_BALANCE', 'Determine SIM balance'), ('GET_PHONE_NUMBER', 'Determine phone number'), ('CALIBRATE', 'Calibrate sensor'), ('ORIENT', 'Orient sensor')], max_length=32),
        ),
    ]
