# Generated by Django 2.2.17 on 2022-11-08 12:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0034_auto_20221027_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='moisture_threshold',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='fullness',
            name='parsing_metadata_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
