env_name: "Dev"
web_app_version: "latest"
web_db_url: "postgres://binology-dev:SZW0MeGK2rPm9i1b3eDYECYt@rc1a-83dfod75ossq02ev.mdb.yandexcloud.net:6432/binology_web_dev"
redis_host_name: "redis-host"
mqtt_broker_host: "mqtt-broker2"
mqtt_username: "mqtt-listener"
mqtt_password: "0i6ULDiNXLdtHsz9A02GNo5T"
web_app_virtual_host: "lk.dev.sensortec.ru"
web_app_letsencrypt_host: "lk.dev.sensortec.ru"
web_app_root_url: "https://lk.dev.sensortec.ru"
realtime_api_root_url: "wss://dev.realtime-api.sensortec.ru"
realtime_api_virtual_host: "dev.realtime-api.sensortec.ru"
realtime_api_letsencrypt_host: "dev.realtime-api.sensortec.ru"
sensor_asset_holder_company_id: 1
demo_sandbox_template_company_ids: "[1]"
onesignal_app_id: "0e8606e3-b193-4f20-95b4-badd049030d6"
onesignal_rest_api_key: "e01ea687ecc0471eabfa0c2c3a917dfe"