# Generated by Django 2.2.16 on 2020-09-23 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_company_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTrashbinsLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(default=datetime.date.today, verbose_name='period begin')),
                ('end', models.DateField(verbose_name='period end')),
                ('description', models.CharField(blank=True, max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='company')),
            ],
        ),
    ]
