- name: Ensure /opt/binology-saas directory exists
  file:
    path: /opt/binology-saas
    state: directory
    mode: '0755'

- name: Copy docker-compose files
  copy:
    src: "{{ item }}"
    dest: "/opt/binology-saas/{{ item }}"
    mode: '0644'
  with_items:
    - docker-compose.database.yml
    - docker-compose.mqtt2.yml
    - docker-compose.reverse-proxy.yml
    - docker-compose.web-app.yml

- name: Generate .env file from template
  template:
    src: env.j2
    dest: /opt/binology-saas/.env
    mode: '0644'
