name: 'Build new image'
description: 'Builds & pushes new Docker image from the Dockerfile specified'
inputs:
  dockerhub-username:
    description: 'Username for Docker Hub'
    required: true
  dockerhub-password:
    description: 'Password or PAT for Docker Hub'
    required: true
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: true
  image-repo:
    description: 'The repo of the image to push to'
    required: true
  image-tag:
    description: 'The tag of the image to build'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ inputs.image-repo }}:${{ inputs.image-tag }}
