# Generated by Django 2.2.10 on 2020-02-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    state_operations = [
        migrations.AddField(
            model_name='city',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='city',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
        migrations.AlterModelTable(
            name='featureflag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userstocompany',
            table=None,
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
