# Generated by Django 2.2.10 on 2020-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
