# Generated by Django 2.2.12 on 2020-05-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userstocompany_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstocompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='userstocompany',
            name='role',
            field=models.CharField(choices=[('SA', 'administrator'), ('OP', 'operator'), ('DR', 'driver')], db_index=True, max_length=2, verbose_name='role'),
        ),
    ]
