# Generated by Django 2.2.13 on 2020-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200507_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='feature',
            field=models.CharField(choices=[('AIR_QUALITY', 'air_quality'), ('CHANGE_PASSWORD', 'change password'), ('EFFICIENCY_MONITOR', 'efficiency monitor')], max_length=128, verbose_name='feature'),
        ),
    ]
