# Generated by Django 2.2.13 on 2020-07-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200728_1337'),
        ('app', '0096_auto_20200728_1329'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='title')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'sector',
                'verbose_name_plural': 'sector',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
