# Generated by Django 2.2.16 on 2020-09-22 11:30

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wastetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lang',
            field=models.CharField(default='en', max_length=20, validators=[apps.core.models.validate_lang]),
        ),
    ]
