# Generated by Django 2.2.16 on 2020-10-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201008_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySubscription',
        ),
    ]
