# Generated by Django 2.2.16 on 2020-10-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_companysubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='feature',
            field=models.CharField(choices=[('AIR_QUALITY', 'Air quality'), ('CHANGE_PASSWORD', 'Change password'), ('EFFICIENCY_MONITOR', 'Efficiency monitor'), ('FULLNESS_FORECAST', 'Fullness forecast')], max_length=128),
        ),
    ]
