# Generated by Django 2.2.17 on 2022-11-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210224_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='feature',
            field=models.CharField(choices=[('AIR_QUALITY', 'Air quality'), ('CHANGE_PASSWORD', 'Change password'), ('EFFICIENCY_MONITOR', 'Efficiency monitor'), ('FULLNESS_FORECAST', 'Fullness forecast'), ('MOISTURE_DROP', 'Drop moisture')], max_length=128),
        ),
    ]
