# Generated by Django 2.2.10 on 2020-02-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20190923_1134_squashed_0083_auto_20200128_0802'),
    ]

    database_operations = [
        migrations.AlterModelTable('City', 'core_city'),
        migrations.AlterModelTable('Company', 'core_company'),
        migrations.AlterModelTable('Country', 'core_country'),
        migrations.AlterModelTable('UsersToCompany', 'core_userstocompany'),
        migrations.AlterModelTable('FeatureFlag', 'core_featureflag'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='container',
            name='city',
        ),
        migrations.RemoveField(
            model_name='container',
            name='company',
        ),
        migrations.RemoveField(
            model_name='container',
            name='country',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='company',
        ),
        migrations.RemoveField(
            model_name='routesdrivers',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sectors',
            name='company',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
        migrations.DeleteModel(
            name='UsersToCompany',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
