# Generated by Django 2.2.10 on 2020-02-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('app', '0084_auto_20200210_0656'),
    ]

    state_operations = [
        migrations.AddField(
            model_name='container',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.City', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='container',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='routes',
            name='company',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routesdrivers',
            name='company',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectors',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='company'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
