# Generated by Django 2.2.16 on 2020-09-30 08:44

import apps.core.models
import django.contrib.auth.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20200210_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='sector',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='company', on_delete=django.db.models.deletion.PROTECT, to='app.Sectors', verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='container',
            name='phone_number',
            field=models.CharField(max_length=40, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='containertype',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='containertype',
            name='description_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='containertype',
            name='description_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='SlackEnabledTrashbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrashbinJobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('mtime', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, choices=[('PRESS_CONTROL', 'Press Control'), ('DOWNLOAD_FIRMWARE', 'Download Firmware'), ('DOWNLOAD_AD', 'Download Advertising'), ('CONNECT_TO_VPN', 'Connect to VPN'), ('UPDATE_CONFIG', 'Update Configuration')], max_length=32)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('SUCCESS', 'Successful job'), ('FAILURE', 'Failed job')], max_length=16)),
                ('execution_description', models.TextField(blank=True)),
                ('trashbin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Container')),
            ],
            options={
                'db_table': 'api_jobs',
                'ordering': ('-ctime',),
            },
        ),
        migrations.CreateModel(
            name='TrashbinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('trashbin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Container')),
            ],
            options={
                'ordering': ('-ctime',),
            },
        ),
        migrations.CreateModel(
            name='CreateDemoSandboxRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Succeed'), (2, 'Failed')], default=0)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('mtime', models.DateTimeField(blank=True, null=True, verbose_name='modified at')),
                ('company_name', models.CharField(max_length=128)),
                ('username_prefix', models.CharField(max_length=80, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('admin_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='username')),
                ('admin_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('lang', models.CharField(default='en', max_length=20, validators=[apps.core.models.validate_lang])),
            ],
        ),
        migrations.RenameField(
            model_name='fullnessstats',
            old_name='containerid',
            new_name='container',
        ),
        migrations.RemoveField(
            model_name='sectors',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sectors',
            name='name_ru',
        ),
        migrations.CreateModel(
            name='DemoSandboxTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('object_type', models.CharField(choices=[('CONTAINER', 'Container'), ('SECTOR', 'Sector')], default='CONTAINER', max_length=32)),
            ],
            options={
                'unique_together': {('object_type', 'object_id', 'lang', 'key')},
            },
        ),
        migrations.AlterModelOptions(
            name='simbalance',
            options={'ordering': ('ctime',), 'verbose_name': 'sim balance', 'verbose_name_plural': 'sim balance'},
        ),
        migrations.AlterField(
            model_name='container',
            name='data_mtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='update time'),
        ),
        migrations.AlterField(
            model_name='containerauthtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
