# Generated by Django 2.2.13 on 2020-07-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20200211_1518_squashed_0095_auto_20200507_0825'),
    ]

    database_operations = [
        migrations.AlterModelTable('Sectors', 'core_sectors'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='container',
            name='sector',
        ),
        migrations.DeleteModel(
            name='Sectors',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
