# Generated by Django 2.2.13 on 2020-07-28 13:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sectors'),
        ('app', '0096_auto_20200728_1329'),
    ]

    state_operations = [
        migrations.AddField(
            model_name='container',
            name='sector',
            field=smart_selects.db_fields.GroupedForeignKey(default=None, group_field='company',
                                                            on_delete=django.db.models.deletion.PROTECT,
                                                            to='core.Sectors', verbose_name='sector'),
            preserve_default=False,
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
