# Generated by Django 2.2.13 on 2020-07-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_sensor_sector'),
        ('app', '0097_container_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepoints',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routepoints', to='sensors.Sensor', verbose_name='sensor'),
        ),
        migrations.AlterField(
            model_name='routepoints',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routepoints', to='app.Container', verbose_name='container'),
        ),
        migrations.AddConstraint(
            model_name='routepoints',
            constraint=models.CheckConstraint(check=models.Q(('container__isnull', False), ('sensor__isnull', False), _connector='OR'), name='either_container_or_sensor_specified'),
        ),
    ]
