# Generated by Django 2.2.13 on 2020-08-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_auto_20200730_0956'),
    ]

    database_operations = [
        migrations.AlterModelTable('WasteType', 'core_wastetype'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='container',
            name='waste_type',
        ),
        migrations.DeleteModel(
            name='WasteType',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
