# Generated by Django 2.2.13 on 2020-08-28 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_container_waste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdemosandboxrequest',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='createdemosandboxrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Succeed'), (2, 'Failed'), (3, 'In progress')], default=0),
        ),
    ]
