# Generated by Django 2.2.16 on 2020-10-08 12:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_auto_20200828_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={},
        ),
        migrations.AlterModelOptions(
            name='containerauthtoken',
            options={},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='energyefficiencyforcontainer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='energyefficiencyprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='error',
            options={'ordering': ('ctime',)},
        ),
        migrations.AlterModelOptions(
            name='errortype',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('ctime',)},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('-ctime',)},
        ),
        migrations.AlterModelOptions(
            name='routepoints',
            options={'ordering': ('-ctime',)},
        ),
        migrations.AlterModelOptions(
            name='simbalance',
            options={'ordering': ('ctime',)},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ('ctime',)},
        ),
        migrations.AlterField(
            model_name='container',
            name='air_quality',
            field=models.IntegerField(default=0, verbose_name='air_quality'),
        ),
        migrations.AlterField(
            model_name='container',
            name='autogenerate_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='max_volume',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='container',
            name='traffic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='createdemosandboxrequest',
            name='mtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demosandboxtranslation',
            name='object_type',
            field=models.CharField(choices=[('CONTAINER', 'Container'), ('SECTOR', 'Sector')], max_length=32),
        ),
        migrations.AlterField(
            model_name='energyefficiencyforcontainer',
            name='ef_last_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energyefficiencyforcontainer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='app.EnergyEfficiencyProfile'),
        ),
        migrations.AlterField(
            model_name='energyefficiencyforcontainer',
            name='turn_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='battery_capacity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='battery_charge_change_window_days',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='battery_max_voltage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='battery_min_voltage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='battery_nominal_voltage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='discharge_per_press',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='discharge_per_standby_day',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='min_temperature_for_charging',
            field=models.SmallIntegerField(default=-10),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='sleep_period_start',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='sleep_period_stop',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='energyefficiencyprofile',
            name='standby_days_stop',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Equipment'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='parent_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_route', to='app.Routes'),
        ),
        migrations.AlterField(
            model_name='routepoints',
            name='mtime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='routepoints',
            name='parent_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_parent_route', to='app.Routes'),
        ),
        migrations.AlterField(
            model_name='routepoints',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_route', to='app.Route'),
        ),
    ]
