# Generated by Django 2.2.16 on 2020-10-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_createdemosandboxrequest_template_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demosandboxtranslation',
            name='object_type',
            field=models.CharField(choices=[('CONTAINER', 'Container'), ('SECTOR', 'Sector'), ('SENSOR', 'Sensor')], max_length=32),
        ),
    ]
